app/main/routes.py
# main/routes.py
from flask import render_template, request, Blueprint
from app.models import Post 

main = Blueprint('main', __name__)

@main.route("/")
def index():
    """Show user homepage"""
    
    return render_template("index.html")

@main.route("/wwb")
def wwb():
    return render_template("wwb.html")

@main.route("/leadership")
def leadership():
    return render_template("leadership.html")

@main.route("/student_leadership")
def student_leadership():
    return render_template("student_leadership.html")

@main.route("/sundays")
def sundays():
    return render_template("sundays.html")

@main.route("/general_events")
def general_events():
    return render_template("general_events.html")

@main.route("/special_events")
def special_events():
    return render_template("special_events.html")

@main.route("/church_events")
def church_events():
    return render_template("church_events.html")

@main.route("/become_a_member")
def become_a_member():
    return render_template("become_a_member.html")

@main.route("/serve_nomember")
def serve_nomember():
    return render_template("serve_nomember.html")

app/posts/routes.py
# posts/routes.py
from flask import (render_template, url_for, flash,
                    redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app import db 
from app.models import Post
from app.posts.forms import PostForm 

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required 
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success') 
        return redirect(url_for('posts.announcements'))
    return render_template('create_post.html', form=form, legend="New Post")

@posts.route("/announcements", methods=['GET', 'POST'])
@login_required
def announcements():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('announcements.html', posts=posts)

@posts.route("/post/<int:post_id>")
@login_required 
def announcement_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('announcement_post.html', post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # 403 is the http response for forbidden route 
        abort(403) 
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        # No need for an add, because these are already in the database. we're just updating something in the db 
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.announcement_post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', form=form, legend="Update Post")
    
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # 403 is the http response for forbidden route 
        abort(403) 
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('posts.announcements'))

app/users/routes.py
# users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required 
from app import db, bcrypt
from app.models import User, Post 
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                            RequestResetForm, ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()

    # If the form validates correctly on submission 
    if form.validate_on_submit():
        # Use a flash message - a one time alert. need to import flash from flask 
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

@users.route("/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # args is a dictionary. get method returns None if the next key doesn't exist 
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Invalid Login. Please check email and password', 'danger')
    return render_template('login.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required 
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data 
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success') 
        return redirect(url_for('users.account'))
        # Post get redirect thing - are you sure you want to reload? The browser says you're about to run ANOTHER post request when you reload the page. 
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/profile_pics/' + current_user.image_file)
    return render_template('account.html', image_file=image_file, form=form)

@users.route("/user/<string:username>", methods=['GET', 'POST'])
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    # Use the function in the other doc. We want to see if there IS a user 
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token!', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # Use a flash message - a one time alert. need to import flash from flask 
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

app/templates/account.html
{% extends "layout.html" %}

{% block title %}
Account
{% endblock %}

{% block main %}
<div class="container" style="padding:30px; margin:20px">
    <div class="row gray2" style="margin:20px; padding:20px">
        <div class="col-2">
            <img class="rounded-circle account-img" style="width:100px" src="{{ image_file }}">
        </div>
        <div class="col-10">
            <div class="media-body" style="padding-top:20px">
                <h2 class="media-heading">{{ current_user.username }}</h2>
                <h2 class="text-secondary">{{ current_user.email }}</h2>
            </div>
        </div>
    </div>
    <div class="content-section gray2" style="margin:20px">
        <form action="" method="post" style="padding:20px" enctype="multipart/form-data">
            {{ form.hidden_tag() }} <!--adds a CSRF token. protects from attacks -->
            <fieldset class="form-group" style="padding:30px">
                <legend class="border-bottom, mb-4">Update Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    
                    {% if form.username.errors %} 
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.username(class="form-control form-control-lg", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.email(class="form-control form-control-lg", autocomplete="off")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }} <br>
                    {{ form.picture(class="form-control-file") }} 
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span> <br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group text-center">
                {{ form.submit(class="btn btn-outline-light") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/announcements.html
{% extends "layout.html" %}

{% block title %}
Announcements
{% endblock %}

{% block main %}

{% for post in posts.items %}
<div class="row gray2" style="margin-top:20px; margin-left:60px; margin-right:60px; padding:20px">
    <div class="col-6">
        <img src="{{ url_for('static', filename='images/profile_pics/' + post.author.image_file) }}"
            class="rounded-circle article-img" style="width:50px; margin:5px">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="">{{
            post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <hr style="margin:3px">
</div>
<div class="row gray2" style="margin-left:60px; margin-right:60px;">
    <div class="col">
        <h2 style="padding-left:20px; padding-top:0px; margin-top:0px"><a class=""
                href="{{ url_for('posts.announcement_post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</div>
</div>
{% endfor %}
<div class="text-center" style="padding:20px">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
    {% if page_num %}
    {% if posts.page == page_num %}
    <a class="text-center btn btn-light mb-4" href="{{ url_for('posts.announcements', page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="text-center btn btn-outline-light mb-4" href="{{ url_for('posts.announcements', page=page_num) }}">{{ page_num
        }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>

<!--
{% for post in posts %}
<h1> {{ post.title }} </h1>
<p>By {{ post.author }} on {{ post.date_posted }}</p>
<p> {{ post.content }} </p>
{% endfor %}
-->

{% endblock %}

app/templates/apology.html
r{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <!-- https://memegen.link/ -->
    <img alt="{{ top }}" class="border img-fluid" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
{% endblock %}

app/templates/change_password.html
{% extends "layout.html" %}

{% block title %}
    Buy
{% endblock %}

{% block main %}
    <div class="mb-3">
        <h2>Change Password</h2>
    </div>
    <form action="/change_password" method="post">
        <div class="mb-3">
            <input autocomplete="off" autofocus class="form-control mx-auto w-auto" id="old_password" name="old_password" placeholder="Old Password" type="password">
        </div>
        <div class="mb-3">
            <input autocomplete="off" autofocus class="form-control mx-auto w-auto" id="new_password" name="new_password" placeholder="New Password" type="password">
        </div>
        <div class="mb-3">
            <input autocomplete="off" autofocus class="form-control mx-auto w-auto" id="verify_new_password" name="verify_new_password" placeholder="Retype New Password" type="password">
        </div>
        <button class="btn btn-primary" type="submit">Change Password</button>
    </form>
{% endblock %}

app/templates/church_events.html
{% extends "layout.html" %}

{% block title %}
Church Events
{% endblock %}

{% block main %}
<div class="fadeInBottom background-image-8">
    <div class="header" style="padding-top:50px">CHURCH EVENTS</div>
</div>
{% endblock %}

app/templates/create_post.html
{% extends "layout.html" %}

{% block title %}
Create a Post
{% endblock %}

{% block main %}
<form action="" method="post" novalidate style="padding:100px">
    {{ form.hidden_tag() }}
    <!--adds a CSRF token. protects from attacks -->
    <fieldset class="form-group">
        <legend class="border-bottom, mb-4">{{ legend }}</legend>

        <div class="form-group">
            {{ form.title.label(class="form-control-label") }}
            {% if form.title.errors %}
            {{ form.title(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
                {{ form.title(class="form-control form-control-lg", autocomplete="off")}}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.content.label(class="form-control-label") }}
            {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
                {{ form.content(class="form-control form-control-lg")}}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-light") }}
    </div>
</form>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}

{% block title %}
    Homepage
{% endblock %}

{% block main %}
    
<div class="holder">
    <div class="fadeInBottom background-image">
        <div class="header">WELCOME</div>
        <a type="button" class="btn-image btn-lg btn btn-outline-light" href="{{ url_for('main.sundays') }}" style="transform:translate(-150%, 200%)">Sunday Service</a>
        <a type="button" class="btn-image btn-lg btn btn-outline-light" href="{{ url_for('main.wwb') }}">About Us</a>
        <a type="button" class="btn-image btn-lg btn btn-outline-light" href="{{ url_for('main.become_a_member') }}" style="transform:translate(55%, 200%)">Get Involved</a>
    </div>
</div>

<div class="header gray2">OUR MINISTRY</div>

<section class="image-view gray1">
<div id="carouselExampleIndicators" class="tag carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
        <img src="/static/images/icfgroupphoto.jpg" class="d-block w-100 carousel-image" alt="ICF 2022 Retreat">
        </div>
        <div class="carousel-item">
        <img src="/static/images/icfgroupphoto2.jpg" class="d-block w-100 carousel-image" alt="ICF Family Camp">
        </div>
        <div class="carousel-item">
        <img src="/static/images/icfgroupphoto3.jpg" class="d-block w-100 carousel-image" alt="ICF Baptisms">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
    </div>
</section>

<div class="header gray2">OUR MISSION</div>

<div class="gray1">
    <p style="text-align: center; font-size:250%; padding-top:80px; padding-bottom:0px">"Him we proclaim, warning everyone and teaching everyone</p>
    <p style="text-align: center; font-size:250%; padding:0px">with all wisdom, that we may present everyone mature in Christ."</p>
    <p style="text-align: center; font-size:250%; padding:20px">Colossians 1:28</p>
    <p style="padding:50px; padding-left:150px; padding-right:150px">Immanuel Christian Fellowship (ICF) is the college ministry of Immanuel Bible Church. Our desire is to connect college students to the local church, proclaiming Christ to them with a high view of God and of Scripture, so that each one would be mature in Christ. Our aim is to equip these students to serve Christ and His church, and to evangelize students who are lost without Christ.</p>
</div>

<div class="header gray2">OUR MEANS</div>

<div class="image-view gray1">
    <div class="row justify-content-center text-center">
        <div class="col">
            <div class="card text-white gray2 mb-3">
                <img src="/static/images/icfgradbrunch.jpg" class="card-img-top img-fluid" alt="ICF Grad Brunch">
                <div class="card-body basic-text">
                    <h5 class="card-title" style="font-size:250%">Join Us On Sunday!</h5>
                    <p class="card-text" style="padding-top:10px; padding-bottom:20px">
                    We provide rides to Immanuel Bible Church every Sunday. You can sign up for a ride here if you want to come to church (sign up by Friday night)! A typical Sunday service is from 9am to 10:30am, with an Equip Hour (more teaching) from 11am to 12pm.
                    </p>
                    <a href="/sundays" target="_blank" class="btn btn-outline-light">Sunday Service</a>
                    <a href="https://docs.google.com/forms/d/e/1FAIpQLSfjOKT6_yMXv6Zd47cGVgrPWIPf43g_UqdCQ8GOibKgSQNRDw/viewform" target="_blank" class="btn btn-outline-info">Rides From UCLA</a>
                    <a href="https://docs.google.com/forms/d/e/1FAIpQLScRpomXatgwd5_VPTa6Ieq4CUfYswsc6w2c-1ktV6oMkFlXjw/viewform" target="_blank" class="btn btn-outline-danger">Rides From USC</a>
                </div>
            </div>
        </div>
    </div>
</div>
    

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>

<html lang="en">

<head>

    <!-- set correct viewport -->
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">

    <!-- get JS files -->
    <script src="/static/js/webscript.js"></script>
    <script src="/static/js/jquery-3.6.1.js"></script>
    <script src="/static/js/test.js"></script>
    <script src="//code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>

    <!-- http://getbootstrap.com/docs/5.1/ -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    
    <!-- get CSS stylesheets -->
    <link href="/static/styles.css" rel="stylesheet">

    <!-- get favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon-16x16.png">
    <link rel="manifest" href="/static/site.webmanifest">

    <title>Immanuel Christian Fellowship: {% block title %}{% endblock %}</title>

</head>

<body class="body text">

    <nav class="navbar navbar-expand-lg navbar-dark gray1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index') }}""><span class="small me-auto mb-2 mb-lg-0">Immanuel Christian
                    Fellowship</span></a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if current_user.is_authenticated %} 
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="aboutDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false" href="#">Announcements</a>
                        <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('posts.announcements') }}">All Announcements</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('posts.new_post') }}">Create Announcement Post</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="aboutDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false" href="#">About</a>
                        <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('main.wwb') }}">What We Believe</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.sundays') }}">Sunday Service</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.leadership') }}">Staff Leadership</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.student_leadership') }}">Student Leadership</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="announcementsDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Events
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="announcementsDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('main.general_events') }}">General Events</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.special_events') }}">Special Events</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.church_events') }}">Church-Wide Events</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="announcementsDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Get Involved
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="announcementsDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('main.become_a_member') }}">Become a Member</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.serve_nomember') }}">Serve</a></li>
                        </ul>
                    </li>
                </ul>


                <ul class="navbar-nav ms-auto mt-2">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.account') }}">Account</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
                </ul>

                {% else %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="aboutDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false" href="#">About</a>
                        <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('main.wwb') }}">What We Believe</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.sundays') }}">Sunday Service</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.leadership') }}">Staff Leadership</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.student_leadership') }}">Student Leadership</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="announcementsDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Events
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="announcementsDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('main.general_events') }}">General Events</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.special_events') }}">Special Events</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.church_events') }}">Church-Wide Events</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="announcementsDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Get Involved
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="announcementsDropdown">
                            <li><a class="dropdown-item" href="{{ url_for('main.become_a_member') }}">Become a Member</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.serve_nomember') }}">Serve</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-expanded="false" href="{{ url_for('users.register') }}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
                    </li>
                </ul>

                {% endif %}
            </div>
        </div>
    </nav>

    <main>
        <div class="row">
            <div class="col-md">
                {% with messages = get_flashed_messages(with_categories=true) %} 
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}" style="margin:0px">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        {% block main %}{% endblock %}
    </main>

    <footer>
        <pre>
            © 2022 Immanuel Bible Church
            15204 Plummer St., North Hills, CA 91343
            (424)261-4222
            info@ibcbible.org
        </pre>
    </footer>
</body>

</html>